### ISSUE TITLE
"import" rather than "require"

### ISSUE THREAD

**Issue by abelta** [leebyron/mocha-check#4]
Recommended way to include the library in a test file seems to be `require('mocha-testcheck').install()` but shouldn't it have a more ES6-like alternative like `import { check } from 'mocha-testcheck'`?

**Comment by abelta** [comment]
Nevermind. I see I can do `import { check, gen } from 'mocha-testcheck'`.
Functionality is unfortunatelly different than when using `.install()`, though.

**Comment by leebyron** [comment]
`.install()` places the mocha check generators into mocha's global context, which is how the `check.it` behavior is done correctly.
